
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bkbrnr_development

test:
  <<: *default
  database: bkbrnr_test

production:
  <<: *default
  database: bkbrnr.com_production
